BOT_TOKEN:
   - MTA5ODg3OTUwNzY5NzUxMjQ1OQ.GhTtgm._cpnnE0cGOU5FXrY_plXcxGUvkcgj3ctCjKF1s
  
CHANNEL_ID: 
  - 1109871707050758247
  
MODE: custom
REPLY: 
SIMSIMI_LANG: id
DELAY: 
DEL_AFTER: 
REPOST_LAST_CHAT: 