BOT_TOKEN:
   - MTA5ODg2NzI1MDI5Mjg2NzEwNg.GXjcaG.EuM_lmU_uHA2WCAjk7XGAusDDrsd3dpHfKmPUA
  
CHANNEL_ID: 
  - 1109871707050758247
  
MODE: custom
REPLY: 
SIMSIMI_LANG: id
DELAY: 
DEL_AFTER: 
REPOST_LAST_CHAT: 